spring:
  application:
    name: file-server
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
admin:
  init:
    password: ${ADMIN_INITIAL_PWD}
storage:
  location: ${LOCATION:./uploads}
